---
- hosts: all
  become: true
  become_user: root

  pre_tasks:

    - name: Install Dependencies
      package:
        name:
          - 'acl'
          - 'bzip2'
          - 'git'
          - 'make'
          - 'python3-psycopg2'
          -  'tar'
          - 'virtualenv'
          - slurm-wlm
          - slurm-drmaa-dev
          - python-psutil

  roles:
    - role: clean_galaxykickstart
      when: galaxykickstart_to_gravity
    - role: galaxyproject.postgresql
      when: install_postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - role: ansible-slurm
      become: true
      when: install_slurm
    - role: installUptime
      when: install_uptime

  post_tasks:

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: not nginx_supervisor
