---
- hosts: dbservers
  become: true
  become_user: root
  pre_tasks:
    - name: Install Dependencies
      package:
        name: 'acl'
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres

- hosts: all
  become: true
  become_user: root

  pre_tasks:
    - name: Add custom slurm PPA (used for Slurm DRMAA package)
      apt_repository:
        repo: ppa:natefoo/slurm-drmaa
        state: present
        update_cache: yes
      when: install_slurm

    - name: Install Dependencies
      package:
        name:
          - 'acl'
          - 'bzip2'
          - 'git'
          - 'make'
          -  'tar'
          - 'python3-venv'
          - 'python3-setuptools'
          - slurm-wlm
          - slurm-drmaa-dev
          - python-psutil

  roles:
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - role: ansible-slurm
      become: true
      when: install_slurm
    - role: installUptime
      when: install_uptime

  post_tasks:

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: not nginx_supervisor
