---
- hosts: dev_gce
  become: true
  become_user: root

  vars_files:
    - group_vars/secret.yml

  pre_tasks:

    - name: Add custom slurm PPA (used for Slurm DRMAA package)
      apt_repository: 
        repo: ppa:natefoo/slurm-drmaa
        state: present
        update_cache: yes

    - name: Install Dependencies
      package:
        name:
          - 'acl'
          - 'bzip2'
          - 'git'
          - 'make'
          - 'python3-psycopg2'
          -  'tar'
          - 'virtualenv'
          - slurm-wlm
          - slurm-drmaa-dev
          - python-psutil
  roles:
    - role: clean_galaxykickstart
      when: galaxykickstart_to_gravity
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - role: ansible-slurm
      become: true

  post_tasks:

    - name: reload nginx at end
      service:
        name: nginx
        state: reloaded
      when: not nginx_supervisor

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: not nginx_supervisor
