- src: galaxyproject.galaxy
  version: 0.10.14
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.0.3
- src: galaxyproject.postgresql_objects
  version: 1.1.0
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: https://github.com/ARTbio/ansible-slurm.git
  name: ansible-slurm
  version: artbio
- src: https://github.com/ARTbio/ansible-galaxy-tools.git
  name: install.galaxy-tools
