---
- name: dump all
  hosts: all
 
  tasks:

    - name: Print HOST Variables
      vars: 
        msg: |
          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_yaml }} 
    
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
