- name: Stop all supervisorctl processes
  supervisorctl:
    name: all
    state: absent

- name: Stop and deregister supervisorctl
  ansible.builtin.systemd:
    name: supervisor.service
    state: stopped
    enabled: false

- name: Stop and deregister slurmctld
  ansible.builtin.systemd:
    name: slurmctld.service
    state: stopped
    enabled: false

- name: Stop and deregister slurmd
  ansible.builtin.systemd:
    name: slurmd.service
    state: stopped
    enabled: false

- name: Remove and purge supervisor
  ansible.builtin.apt:
    name: supervisor
    state: absent
    purge: true

- name: Remove and purge munge
  ansible.builtin.apt:
    name: munge
    state: absent
    purge: true

- name: Remove and purge nginx
  ansible.builtin.apt:
    name: nginx-common
    state: absent
    purge: true
