- name: Stop all supervisorctl processes
  supervisorctl:
    name: all
    state: absent

- name: Stop and deregister supervisorctl
  ansible.builtin.systemd:
    name: supervisor.service
    state: stopped
    enabled: false

- name: Remove and purge nginx
  ansible.builtin.apt:
    name: nginx-common
    state: absent
    purge: true

- name: remove ppa:natefoo/slurm-drmaa (will be reinstalled)
  ansible.builtin.apt:
    repo: ppa:natefoo/slurm-drmaa
    state: absent

- name: Remove slurm-drmaa (will be reinstalled)
  ansible.builtin.apt:
    name: slurm-drmaa
    state: absent
    purge: true

- name: Remove munge (will be reinstalled)
  ansible.builtin.apt:
    name: munge
    state: absent
    purge: true

