install_uptime: no
uptime_dir: "{{ galaxy_root }}"
uptime_user: "{{ galaxy_user.name }}"
service_description: "A service to run uptime.sh and publish server usage image through galaxy nginx"

uptime_templates:
  - src: uptime.R.j2
    dest: "{{ uptime_dir }}/uptime.R"
  - src: uptime.sh.j2
    dest: "{{ uptime_dir }}/uptime.sh"
