- name: Install R for usage plot
  package:
    name:
      - 'r-base'

- name: Create an uptime directory
  become_user: "{{ uptime_user }}"
  file:
    path: "{{ galaxy_root }}"
    state: directory

- name: Instantiate uptime templates
  become_user: "{{ uptime_user }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    mode: "{{ galaxy_config_perms }}"
  with_items: "{{ uptime_templates }}"
  
- name: Create uptime systemd service file
  template:
    src: templates/uptime.service.j2
    dest: /lib/systemd/system/uptime.service

- name: Start uptime service
  systemd:
    name: uptime
    state: started
