- name: Install R for usage plot
  package:
    name:
      - 'r-base'

- name: Instantiate uptime templates
  become_user: 'galaxy'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    mode: "{{ galaxy_config_perms }}"
  with_items: "{{ uptime_templates }}"

- name: galaxyctl supervisorctl reload
  command: "{{ galaxy_venv_dir }}/bin/galaxyctl supervisorctl reload"
  environment:
    GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
