tools:
- name: split_file_to_collection
  owner: bgruening
  tool_panel_section_label: Collection Operations
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: column_maker
  owner: devteam
  tool_panel_section_label: Text Manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: concatenate_multiple_datasets
  owner: artbio
  tool_panel_section_label: Text Manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: regex_find_replace
  owner: galaxyp
  tool_panel_section_label: Text Manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: annotatemyids
  owner: iuc
  tool_panel_section_label: Convert Formats
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: vcf2maf
  owner: iuc
  tool_panel_section_label: Convert Formats
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: fastqc
  owner: devteam
  tool_panel_section_label: Biotechnologie_M2
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: fasta_compute_length
  owner: devteam
  tool_panel_section_label: Biotechnologie_M2
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: small_rna_maps
  owner: artbio
  tool_panel_section_label: Biotechnologie_M2
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: yac_clipper
  owner: artbio
  tool_panel_section_label: Biotechnologie_M2
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: sr_bowtie_dataset_annotation
  owner: artbio
  tool_panel_section_label: Biotechnologie_M2
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: sr_bowtie
  owner: artbio
  tool_panel_section_label: Biotechnologie_M2
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: sambamba
  owner: artbio
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_view
  owner: iuc
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_stats
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_split
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_sort
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_slice_bam
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_rmdup
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_reheader
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_mpileup
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_idxstats
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_flagstat
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_calmd
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_bedcov
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: sam_to_bam
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bam_to_sam
  owner: devteam
  tool_panel_section_label: SAMTOOLS
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: multiqc
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: nextclade
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: pangolin
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: snpeff_sars_cov_2
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: ivar_consensus
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: ivar_variants
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: ivar_trim
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: qualimap_bamqc
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtools_view
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bwa
  owner: devteam
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: text_processing
  owner: bgruening
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: fastp
  owner: iuc
  tool_panel_section_label: COVID
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: cherry_pick_fasta
  owner: artbio
  tool_panel_section_label: Fasta Manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: lumpy_smoove
  owner: artbio
  tool_panel_section_label: Variants
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: repenrich
  owner: artbio
  tool_panel_section_label: Repenrich
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bowtie2
  owner: devteam
  tool_panel_section_label: 'NGS: align'
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bowtie_wrappers
  owner: devteam
  tool_panel_section_label: 'NGS: align'
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: mapping_quality_stats
  owner: artbio
  tool_panel_section_label: 'NGS: QC and manipulation'
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: seqtk
  owner: iuc
  tool_panel_section_label: 'NGS: QC and manipulation'
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: bcftools_reheader
  owner: iuc
  tool_panel_section_label: bcftools
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: data_manager_sam_fasta_index_builder
  owner: devteam
  tool_panel_section_label: None
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: data_manager_bowtie_index_builder
  owner: iuc
  tool_panel_section_label: None
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: data_manager_fetch_genome_dbkeys_all_fasta
  owner: devteam
  tool_panel_section_label: None
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: data_manager_bwa_mem_index_builder
  owner: devteam
  tool_panel_section_label: None
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: data_manager_bowtie2_index_builder
  owner: devteam
  tool_panel_section_label: None
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: data_manager_vep_cache_downloader
  owner: iuc
  tool_panel_section_label: None
  tool_shed_url: toolshed.g2.bx.psu.edu
